"""Title and intro generation for the weekly digest pipeline.

``DigestFramer`` produces the digest's framing (the H1 title and the lede
paragraph) from the cleaned section drafts. The two are generated by
separate LLM calls with distinct prompts so each can enforce its own
rules without leaking into the other.

Configured via ``FRAMER_MODEL`` environment variable. Falls back to
``WRITER_MODEL`` if unset so the framer rides the same model as the
section writer unless explicitly overridden.
"""

import re
from datetime import UTC, datetime

from ollama import Client

from digest_generator.core.digest.prompts import load_prompt
from digest_generator.core.digest.types import DigestFraming, SectionDraft
from digest_generator.shared.llm.clients import client_registry
from digest_generator.shared.llm.sampling import SamplingConfig, resolve_ollama_options
from digest_generator.shared.llm.telemetry import chat_with_logging
from digest_generator.shared.llm.typography import normalize_typography
from digest_generator.shared.logging import current_span, log_stage, logger
from digest_generator.shared.settings import settings

_TITLE_SYSTEM_PROMPT = load_prompt("title_system")
_INTRO_SYSTEM_PROMPT = load_prompt("intro_system")

_BRAND_LED_VERBS = (
    "Finds",
    "Releases",
    "Launches",
    "Unveils",
    "Announces",
    "Reveals",
    "Drops",
    "Ships",
    "Patches",
    "Debuts",
    "Introduces",
    "Adds",
    "Brings",
    "Delivers",
    "Rolls Out",
)

_FORBIDDEN_TITLE_PATTERNS: tuple[tuple[re.Pattern[str], str], ...] = (
    (
        re.compile(r"^AI\s"),
        "starts with 'AI ' — AI is the digest's topic, not news",
    ),
    (
        re.compile(r"^\w+:\s"),
        "uses the 'X: Y' colon-split format",
    ),
    (
        re.compile(
            r"^(?:[A-Z][a-zA-Z0-9]*\s+){1,3}(?:"
            + "|".join(v.replace(" ", r"\s+") for v in _BRAND_LED_VERBS)
            + r")\s",
        ),
        (
            "leads with a brand/product name plus a generic announcement verb "
            "(e.g. 'OpenAI Releases', 'Claude Mythos Finds') — reads like vendor "
            "marketing, not editorial framing"
        ),
    ),
)


class DigestFramer:
    """Generates the digest title and lede paragraph from cleaned sections.

    Args:
        client: Ollama client instance. Defaults to auto-detected client from
                ``ClientRegistry`` (cloud if ``OLLAMA_API_KEY`` is set, else local).
        model: Ollama model name. Defaults to ``FRAMER_MODEL`` env var, or
               ``WRITER_MODEL`` if ``FRAMER_MODEL`` is unset.
        sampling: Per-call sampling overrides (``temperature``, ``top_p``,
                ``repetition_penalty``, ``seed``). Unset fields fall back to
                the matching ``framer_*`` settings.
    """

    def __init__(
        self,
        client: Client | None = None,
        model: str | None = None,
        sampling: SamplingConfig | None = None,
    ):
        self._client = client or client_registry.ollama
        self.model = model or settings.framer_model or settings.writer_model
        self._sampling = sampling

    def frame(
        self,
        sections: list[SectionDraft],
        *,
        date_range: tuple[str, str] | None = None,
    ) -> DigestFraming:
        """Generate the H1 title and 2-3 sentence lede.

        Returns a ``DigestFraming`` with empty fields if the model returns
        empty output for either call. Callers should surface this as an
        error at the orchestration layer.
        """
        with log_stage("framer") as span:
            title = self._generate_title(sections, date_range=date_range)
            intro = self._generate_intro(sections, title=title, date_range=date_range)
            span.set(
                title_chars=len(title),
                intro_words=len(intro.split()),
                model=self.model,
            )
            return DigestFraming(title=title, intro=intro)

    def _generate_title(
        self,
        sections: list[SectionDraft],
        *,
        date_range: tuple[str, str] | None,
    ) -> str:
        period = _format_period(date_range)
        lines = [
            "<task>",
            f"Generate the title for the weekly digest ({period}).",
            f"You have {len(sections)} section drafts to read across.",
            "</task>",
            "",
        ]
        lines.extend(_format_sections(sections))
        base_user_prompt = "\n".join(lines)

        logger.info("Generating digest title via {}", self.model)
        title = _clean_title(
            normalize_typography(self._call_llm(_TITLE_SYSTEM_PROMPT, base_user_prompt))
        )

        issues = _title_issues(title)
        span = current_span()
        if not issues:
            if span is not None:
                span.set(title_retried=False)
            return title

        if span is not None:
            span.set(title_retried=True, title_retry_reasons="; ".join(issues))
        logger.warning(
            "Title {!r} matched forbidden pattern(s): {} — retrying with feedback",
            title,
            "; ".join(issues),
        )
        retry_user_prompt = f"{base_user_prompt}\n{_build_retry_feedback(title, issues)}"
        retried = _clean_title(
            normalize_typography(self._call_llm(_TITLE_SYSTEM_PROMPT, retry_user_prompt))
        )
        if _title_issues(retried):
            logger.warning(
                "Retried title {!r} still matches forbidden pattern(s) — accepting anyway",
                retried,
            )
        return retried

    def _generate_intro(
        self,
        sections: list[SectionDraft],
        *,
        title: str,
        date_range: tuple[str, str] | None,
    ) -> str:
        period = _format_period(date_range)
        section_summary = ", ".join(f"{s.name} ({s.article_count} articles)" for s in sections)
        lines = [
            "<task>",
            f"Write the 2-3 sentence lede paragraph for the weekly digest ({period}).",
            f'The digest title is: "{title}".',
            f"The digest spans {len(sections)} sections: {section_summary}.",
            "Inspect the title's shape and pick the matching lede structure:",
            "- If the title names a tension or collision (signals: 'Collides with', 'Meets',",
            "  'vs.', 'Outpaces', 'Rises as ... Falls', 'Amid', 'Despite'), use the",
            "  pivot structure — one fact per side, a relationship-naming connector in the",
            "  middle ('Simultaneously,', 'In response,', 'While X, Y'), synthesis to close.",
            "- If the title names a specific event, use the weave structure — open on the event,",
            "  add a complementary fact from another section, close on the implication.",
            "Do not restate the title; do not blend the two structures.",
            "</task>",
            "",
        ]
        lines.extend(_format_sections(sections))
        logger.info("Generating digest intro via {}", self.model)
        raw = self._call_llm(_INTRO_SYSTEM_PROMPT, "\n".join(lines))
        return normalize_typography(raw).strip()

    def _call_llm(self, system_prompt: str, user_prompt: str) -> str:
        options = resolve_ollama_options(
            self._sampling,
            temperature=settings.framer_temperature,
            top_p=settings.framer_top_p,
            repetition_penalty=settings.framer_repetition_penalty,
            seed=settings.framer_seed,
        )
        return chat_with_logging(
            self._client,
            model=self.model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            options=options,
        )


def _format_period(date_range: tuple[str, str] | None) -> str:
    if date_range:
        return f"covering {date_range[0]} to {date_range[1]}"
    return f"week of {datetime.now(tz=UTC).strftime('%Y-%m-%d')}"


def _format_sections(sections: list[SectionDraft]) -> list[str]:
    """Format cleaned section drafts as XML for structured LLM prompts."""
    lines = ["<sections>"]
    for section in sections:
        lines.append("<section>")
        lines.append(f"  <name>{section.name}</name>")
        lines.append(f"  <article-count>{section.article_count}</article-count>")
        lines.append("  <content>")
        lines.append(section.content)
        lines.append("  </content>")
        lines.append("</section>")
    lines.append("</sections>")
    return lines


def _clean_title(raw: str) -> str:
    """Strip whitespace and surrounding quotes from a generated title."""
    title = raw.strip()
    if len(title) >= 2 and title[0] == title[-1] and title[0] in ('"', "'"):
        title = title[1:-1].strip()
    return title


def _title_issues(title: str) -> list[str]:
    """Return reason strings for any forbidden patterns the title matches."""
    return [reason for pattern, reason in _FORBIDDEN_TITLE_PATTERNS if pattern.search(title)]


def _build_retry_feedback(previous: str, issues: list[str]) -> str:
    issues_phrase = " and ".join(issues)
    return (
        "<retry-feedback>\n"
        f'Your previous attempt was: "{previous}"\n'
        f"It {issues_phrase}. Try again, leading with a specific event, entity, or metric "
        "from the sections above. Reread the rules and good-examples in the system prompt "
        "before responding.\n"
        "</retry-feedback>"
    )
